CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    CREATE TABLE "Roles" (
        "RoleId" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleName" character varying(100) NOT NULL,
        "Description" character varying(200),
        "RoleType" text,
        "IsActive" boolean NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL DEFAULT (now()),
        "CreatedBy" text NOT NULL,
        "UpdatedDate" timestamp with time zone,
        "UpdatedBy" text,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("RoleId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    CREATE TABLE "UserStatuses" (
        "UserStatusId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(50) NOT NULL,
        "Color" character varying(20) NOT NULL,
        "Description" character varying(1000),
        "IsActive" boolean NOT NULL,
        "AffectsAccess" boolean NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL DEFAULT (now()),
        "CreatedBy" text NOT NULL,
        "UpdatedDate" timestamp with time zone,
        "UpdatedBy" text,
        CONSTRAINT "PK_UserStatuses" PRIMARY KEY ("UserStatusId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    CREATE TABLE "Users" (
        "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserIdentifier" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserName" character varying(50),
        "Password" text NOT NULL,
        "Email" character varying(255) NOT NULL,
        "RoleId" integer NOT NULL,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "MiddleName" character varying(100),
        "BirthDate" timestamp with time zone,
        "LastLoginDatetime" timestamp with time zone,
        "Gender" character varying(20),
        "BiologicalSex" integer,
        "MobileNumber" character varying(20),
        "Address" character varying(1000),
        "CreatedDate" timestamp with time zone NOT NULL DEFAULT (now()),
        "CreatedBy" text NOT NULL,
        "UpdatedDate" timestamp with time zone,
        "UpdatedBy" text,
        "UserStatusId" integer NOT NULL,
        "RequiredPasswordChange" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") ON DELETE CASCADE,
        CONSTRAINT "FK_Users_UserStatuses_UserStatusId" FOREIGN KEY ("UserStatusId") REFERENCES "UserStatuses" ("UserStatusId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    CREATE TABLE "PasswordResetTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Token" text NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsUsed" boolean NOT NULL,
        CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    INSERT INTO "Roles" ("RoleId", "CreatedBy", "Description", "IsActive", "RoleName", "RoleType", "UpdatedBy", "UpdatedDate")
    VALUES (1, 'System', 'System administrator with full access', TRUE, 'Admin', 'System', NULL, NULL);
    INSERT INTO "Roles" ("RoleId", "CreatedBy", "Description", "IsActive", "RoleName", "RoleType", "UpdatedBy", "UpdatedDate")
    VALUES (2, 'System', 'Standard application user', TRUE, 'User', 'Default', NULL, NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    INSERT INTO "UserStatuses" ("UserStatusId", "AffectsAccess", "Color", "CreatedBy", "Description", "IsActive", "Name", "UpdatedBy", "UpdatedDate")
    VALUES (1, FALSE, '', 'System', 'Default status for active users', TRUE, 'Active', NULL, NULL);
    INSERT INTO "UserStatuses" ("UserStatusId", "AffectsAccess", "Color", "CreatedBy", "Description", "IsActive", "Name", "UpdatedBy", "UpdatedDate")
    VALUES (2, FALSE, '', 'System', 'Default status for inactive users', TRUE, 'Inactive', NULL, NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    INSERT INTO "Users" ("UserId", "Address", "BiologicalSex", "BirthDate", "CreatedBy", "Email", "FirstName", "Gender", "LastLoginDatetime", "LastName", "MiddleName", "MobileNumber", "Password", "RequiredPasswordChange", "RoleId", "UpdatedBy", "UpdatedDate", "UserIdentifier", "UserName", "UserStatusId")
    VALUES (1, NULL, NULL, NULL, 'System', 'admin@example.com', 'System', NULL, NULL, 'Administrator', NULL, NULL, '$2a$12$MZ9oNNn/RfLnn2ipec5FzeeXuTCiHAZDw44Hd3rD8zomXZjOV2Fe6', FALSE, 1, NULL, NULL, '00000000-0000-0000-0000-000000000001', 'admin', 1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    CREATE INDEX "IX_PasswordResetTokens_UserId" ON "PasswordResetTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    CREATE UNIQUE INDEX "IX_Users_UserIdentifier" ON "Users" ("UserIdentifier");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    CREATE UNIQUE INDEX "IX_Users_UserName" ON "Users" ("UserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    CREATE INDEX "IX_Users_UserStatusId" ON "Users" ("UserStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Roles"', 'RoleId'),
        GREATEST(
            (SELECT MAX("RoleId") FROM "Roles") + 1,
            nextval(pg_get_serial_sequence('"Roles"', 'RoleId'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"UserStatuses"', 'UserStatusId'),
        GREATEST(
            (SELECT MAX("UserStatusId") FROM "UserStatuses") + 1,
            nextval(pg_get_serial_sequence('"UserStatuses"', 'UserStatusId'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Users"', 'UserId'),
        GREATEST(
            (SELECT MAX("UserId") FROM "Users") + 1,
            nextval(pg_get_serial_sequence('"Users"', 'UserId'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214095813_Init_Postgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260214095813_Init_Postgres', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214102457_SetCreatedDateNullable') THEN
    ALTER TABLE "UserStatuses" ALTER COLUMN "CreatedDate" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214102457_SetCreatedDateNullable') THEN
    ALTER TABLE "Users" ALTER COLUMN "CreatedDate" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214102457_SetCreatedDateNullable') THEN
    ALTER TABLE "Roles" ALTER COLUMN "CreatedDate" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214102457_SetCreatedDateNullable') THEN
    UPDATE "Roles" SET "CreatedDate" = NULL
    WHERE "RoleId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214102457_SetCreatedDateNullable') THEN
    UPDATE "Roles" SET "CreatedDate" = NULL
    WHERE "RoleId" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214102457_SetCreatedDateNullable') THEN
    UPDATE "UserStatuses" SET "CreatedDate" = NULL
    WHERE "UserStatusId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214102457_SetCreatedDateNullable') THEN
    UPDATE "UserStatuses" SET "CreatedDate" = NULL
    WHERE "UserStatusId" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214102457_SetCreatedDateNullable') THEN
    UPDATE "Users" SET "CreatedDate" = NULL
    WHERE "UserId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214102457_SetCreatedDateNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260214102457_SetCreatedDateNullable', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214103827_ChangeBirthDateToDate') THEN
    ALTER TABLE "Users" ALTER COLUMN "BirthDate" TYPE date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260214103827_ChangeBirthDateToDate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260214103827_ChangeBirthDateToDate', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    ALTER TABLE "Roles" ALTER COLUMN "Description" TYPE character varying(1000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    ALTER TABLE "Roles" ADD "IsSystemRole" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    CREATE TABLE "Modules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(1000) NOT NULL,
        CONSTRAINT "PK_Modules" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    CREATE TABLE "SubModules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ModuleId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(1000) NOT NULL,
        "Code" character varying(200) NOT NULL,
        CONSTRAINT "PK_SubModules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SubModules_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    CREATE TABLE "RolePermissions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" integer NOT NULL,
        "SubModuleId" integer NOT NULL,
        "ModuleId" integer,
        CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RolePermissions_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id"),
        CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") ON DELETE CASCADE,
        CONSTRAINT "FK_RolePermissions_SubModules_SubModuleId" FOREIGN KEY ("SubModuleId") REFERENCES "SubModules" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    INSERT INTO "Modules" ("Id", "Description", "Name")
    VALUES (1, 'Manage people and their access levels to ensure secure and compliant usage of the app', 'User and Access Control');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    UPDATE "Roles" SET "IsSystemRole" = TRUE
    WHERE "RoleId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    UPDATE "Roles" SET "IsSystemRole" = FALSE
    WHERE "RoleId" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    UPDATE "Users" SET "Email" = 'junecanas2@gmail.com'
    WHERE "UserId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    INSERT INTO "SubModules" ("Id", "Code", "Description", "ModuleId", "Name")
    VALUES (1, 'UAC_ASSIGN_ROLES', '', 1, 'Assign Roles');
    INSERT INTO "SubModules" ("Id", "Code", "Description", "ModuleId", "Name")
    VALUES (2, 'UAC_ADD_USER', '', 1, 'Add User');
    INSERT INTO "SubModules" ("Id", "Code", "Description", "ModuleId", "Name")
    VALUES (3, 'UAC_REMOVE_USER', '', 1, 'Remove User');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    INSERT INTO "RolePermissions" ("Id", "ModuleId", "RoleId", "SubModuleId")
    VALUES (1, NULL, 1, 1);
    INSERT INTO "RolePermissions" ("Id", "ModuleId", "RoleId", "SubModuleId")
    VALUES (2, NULL, 1, 2);
    INSERT INTO "RolePermissions" ("Id", "ModuleId", "RoleId", "SubModuleId")
    VALUES (3, NULL, 1, 3);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    CREATE INDEX "IX_RolePermissions_ModuleId" ON "RolePermissions" ("ModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    CREATE INDEX "IX_RolePermissions_RoleId" ON "RolePermissions" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    CREATE INDEX "IX_RolePermissions_SubModuleId" ON "RolePermissions" ("SubModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    CREATE INDEX "IX_SubModules_ModuleId" ON "SubModules" ("ModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Modules"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Modules") + 1,
            nextval(pg_get_serial_sequence('"Modules"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"SubModules"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "SubModules") + 1,
            nextval(pg_get_serial_sequence('"SubModules"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"RolePermissions"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "RolePermissions") + 1,
            nextval(pg_get_serial_sequence('"RolePermissions"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218115658_CreateRolePermission') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260218115658_CreateRolePermission', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218135946_UpdateRolePermissionDefinition') THEN
    ALTER TABLE "RolePermissions" DROP CONSTRAINT "FK_RolePermissions_Modules_ModuleId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218135946_UpdateRolePermissionDefinition') THEN
    DROP INDEX "IX_RolePermissions_ModuleId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218135946_UpdateRolePermissionDefinition') THEN
    ALTER TABLE "RolePermissions" DROP COLUMN "ModuleId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218135946_UpdateRolePermissionDefinition') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260218135946_UpdateRolePermissionDefinition', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260303133205_AddedSubmoduleData') THEN
    INSERT INTO "SubModules" ("Id", "Code", "Description", "ModuleId", "Name")
    VALUES (4, 'UAC_VIEW_USERLIST', '', 1, 'View User list');
    INSERT INTO "SubModules" ("Id", "Code", "Description", "ModuleId", "Name")
    VALUES (5, 'UAC_VIEW_ROLES', '', 1, 'View Roles');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260303133205_AddedSubmoduleData') THEN
    PERFORM setval(
        pg_get_serial_sequence('"SubModules"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "SubModules") + 1,
            nextval(pg_get_serial_sequence('"SubModules"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260303133205_AddedSubmoduleData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260303133205_AddedSubmoduleData', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260308141807_AddedSubmodule') THEN
    INSERT INTO "RolePermissions" ("Id", "RoleId", "SubModuleId")
    VALUES (4, 1, 4);
    INSERT INTO "RolePermissions" ("Id", "RoleId", "SubModuleId")
    VALUES (5, 1, 5);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260308141807_AddedSubmodule') THEN
    PERFORM setval(
        pg_get_serial_sequence('"RolePermissions"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "RolePermissions") + 1,
            nextval(pg_get_serial_sequence('"RolePermissions"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260308141807_AddedSubmodule') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260308141807_AddedSubmodule', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260403061226_AddStatusColor') THEN
    UPDATE "UserStatuses" SET "Color" = 'green'
    WHERE "UserStatusId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260403061226_AddStatusColor') THEN
    UPDATE "UserStatuses" SET "Color" = 'red'
    WHERE "UserStatusId" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260403061226_AddStatusColor') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260403061226_AddStatusColor', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260414131132_FileRecordModuleEntity') THEN
    CREATE TABLE "ModuleDocumentTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ModuleId" integer NOT NULL,
        "DocumentTypeName" character varying(200) NOT NULL,
        "Description" character varying(255),
        CONSTRAINT "PK_ModuleDocumentTypes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ModuleDocumentTypes_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260414131132_FileRecordModuleEntity') THEN
    CREATE TABLE "FileRecords" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FileKey" text NOT NULL,
        "ThumbnailKey" text,
        "OriginalFileName" text NOT NULL,
        "ContentType" character varying(255) NOT NULL,
        "FileSizeBytes" bigint NOT NULL,
        "ModuleId" integer NOT NULL,
        "ReferenceId" integer NOT NULL,
        "ModuleDocumentTypeId" integer NOT NULL,
        "UploadedAt" timestamp with time zone DEFAULT (now()),
        "UploadedBy" text NOT NULL,
        CONSTRAINT "PK_FileRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FileRecords_ModuleDocumentTypes_ModuleDocumentTypeId" FOREIGN KEY ("ModuleDocumentTypeId") REFERENCES "ModuleDocumentTypes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FileRecords_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260414131132_FileRecordModuleEntity') THEN
    INSERT INTO "ModuleDocumentTypes" ("Id", "Description", "DocumentTypeName", "ModuleId")
    VALUES (1, 'Profile pictures uploaded by users for their accounts', 'Profile Picture', 1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260414131132_FileRecordModuleEntity') THEN
    CREATE INDEX "IX_FileRecords_ModuleDocumentTypeId" ON "FileRecords" ("ModuleDocumentTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260414131132_FileRecordModuleEntity') THEN
    CREATE INDEX "IX_FileRecords_ModuleId_ReferenceId" ON "FileRecords" ("ModuleId", "ReferenceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260414131132_FileRecordModuleEntity') THEN
    CREATE UNIQUE INDEX "IX_ModuleDocumentTypes_ModuleId_DocumentTypeName" ON "ModuleDocumentTypes" ("ModuleId", "DocumentTypeName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260414131132_FileRecordModuleEntity') THEN
    PERFORM setval(
        pg_get_serial_sequence('"ModuleDocumentTypes"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "ModuleDocumentTypes") + 1,
            nextval(pg_get_serial_sequence('"ModuleDocumentTypes"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260414131132_FileRecordModuleEntity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260414131132_FileRecordModuleEntity', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418072044_AddProfilePicToUser') THEN
    ALTER TABLE "Users" ADD "ProfilePictureFileRecordId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418072044_AddProfilePicToUser') THEN
    UPDATE "Users" SET "ProfilePictureFileRecordId" = NULL
    WHERE "UserId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418072044_AddProfilePicToUser') THEN
    CREATE INDEX "IX_Users_ProfilePictureFileRecordId" ON "Users" ("ProfilePictureFileRecordId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418072044_AddProfilePicToUser') THEN
    ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_FileRecords_ProfilePictureFileRecordId" FOREIGN KEY ("ProfilePictureFileRecordId") REFERENCES "FileRecords" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418072044_AddProfilePicToUser') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260418072044_AddProfilePicToUser', '9.0.8');
    END IF;
END $EF$;
COMMIT;

